### ISSUE TITLE
All fields are required with simple_form and Rails 5

### ISSUE THREAD

**Issue by wintersolutions** [trailblazer/reform-rails#40]
Given a Form object:

```
class Foo < Reform::Form
  include Reform::Form::ActiveModel::ModelReflections

  property :name, validates: {presence: true}
  property :middle_name, validates: {presence: false}
end
```
and a corresponding `form.haml`:
```
= simple_form_for @form do |form|
  = form.input :name
  = form.input :middle_name
  = form.submit
```

Both fields are marked as required when I view the form.

versions:
* reform 2.2.3
* reform-rails 0.1.7
* simple_form 3.4.0
* rails 5.0.1
* cells-rails 0.0.6
* trailblazer 2.0.1
* trailblazer-rails 1.0.2

**Comment by fran-worley** [comment]
This is nothing to do with rails 5 specifically, it also happens when using reform with dry validations and in cases where you have more complex validations (i.e. conditions).

The simplest solution would be for you to just tell simple form which fields are required manually (`required: true`). 

We won't be doing any more work on making Reform work any better with SimpleForm, but a PR would be welcome if you want to do some digging yourself.
