### ISSUE TITLE
fieldnames in error messages not found via i18n scope

### ISSUE THREAD

**Issue by schorsch** [trailblazer/reform-rails#83]
first: thanks for the update and everybodys work!

I dont know if this ticket belongs here or in the reform main gem, but since i am using ActiveRecord validations i suppose this is right here.

With reform-rails ( v0.2.0 + reform v2.3.1) using model.errors.full_messages the fieldnames with errors are not found within their 'normal' i18n scope which is either de.attributes.a_name or de.activerecord.attributes.my_model.a_name

it seems as if the method here needs to be overridden to make an i18n lookup instead of a simple capitalize https://github.com/trailblazer/reform/blob/master/lib/reform/errors.rb#L29

Does anybody else has this problem? I would probalby go with a monkey patch as a quick solution but this does not feel right.

**Comment by valscion** [comment]
Yeah, we've got the same issue. Seems like changes done in https://github.com/trailblazer/reform-rails/pull/44 have caused this, I think it might be due to how `errors` is now overridden here:

https://github.com/trailblazer/reform-rails/blob/c78a70ff46ea86aafa325b62da7cc8ac717489d7/lib/reform/form/active_model/validations.rb#L119-L122

"not sure this is 100% compatible with AMV::Errors?" comment would point to to this direction, in that overriding `errors` is not compatible with `ActiveModel` validations.

![just_start_rails_and_fieldnames_in_error_messages_not_found_via_i18n_scope_·_Issue__83_·_trailblazer_reform-rails](https://user-images.githubusercontent.com/482561/90227726-b593c680-de1d-11ea-81e7-55da9ade2d40.png)

The controller with bad translations showing up is fairly simple (authorization code removed from here):

```rb
# frozen_string_literal: true
module API
  module Catering
    class InquiriesController < ApplicationController
      def update
        catering_inquiry = ::Catering::Inquiry.find(params[:id])
        form = ::Catering::UpdateInquiryForm.new(catering_inquiry)

        if form.validate(params[:inquiry])
          form.sync
          form.model.save!
          respond_to do |format|
            format.json { render(json: { success: true }) }
          end
        else
          respond_to do |format|
            format.json do
              render(
                json: { message: form.errors.full_messages.to_sentence },
                status: :unprocessable_entity
              )
            end
          end
        end
      end
    end
  end
end
```

and the form itself is also fairly simple:

```rb
# frozen_string_literal: true
module Catering
  class UpdateInquiryForm < Reform::Form
    model :inquiry

    property :company, from: :author_company
    property :author_name
    property :event_at, type: Types::Form::Date

    property :status
    property :rent_fee, type: Types::Form::Float
    property :catering_fee, type: Types::Form::Float
    property :other_fees, type: Types::Form::Float

    validates :status, inclusion: { in: Catering::Inquiry.statuses }
    validates :author_name, presence: true
    validates :event_at, presence: true, date: true
  end
end
```

It seems like this translation isn't getting applied like it did in `reform-rails` v0.1.7:

```yaml
fi:
  attributes:
    author_name: Asiakkaan nimi
```

Proof that it worked in `reform-rails` v0.1.7:

![just_start_rails](https://user-images.githubusercontent.com/482561/90228527-0b1ca300-de1f-11ea-9f61-69ff0b8f849a.png)

**Comment by marcelolx** [comment]
We've this problem too, i send a PR only overriding full_messages to reform-rails delegate the call to AM https://github.com/trailblazer/reform-rails/pull/85, but this doesn't solves the problem for nested model attributes, also I haven't looked at the comment on the code which @valscion highlighted, tomorrow I will take another look to see if that could be handled changing `errors` behavior.

**Comment by marcelolx** [comment]
@schorsch @valscion Could you guys make some tests with the branch of this PR https://github.com/trailblazer/reform-rails/pull/85 to see if the changes solve your problems? Tomorrow I'll do some tests in our application, but I would appreciate if other folks made some tests to make sure I'm not breaking anything on reform-rails.

**Comment by valscion** [comment]
Yeah, we can test it :) — a few little things are currently in progress so we might not be able to get to it today already, but hopefully we'll get to testing it during this working week still.

**Comment by valscion** [comment]
Based on a quick test #85 would seem to work ☺️.

![Sanitized_Author_-_Venuu_fi](https://user-images.githubusercontent.com/482561/96728109-743f0a80-13bc-11eb-909e-03689d2fec57.png)

For reference, here's the same page with `reform-rails` using v0.2.0:

![broken_reform-rails](https://user-images.githubusercontent.com/482561/96728126-7739fb00-13bc-11eb-9244-307761c57378.png)

**Comment by marcelolx** [comment]
@valscion Thanks for the tests ❤️
